version = 3

[upgrade]
  source = 'cdn'
  interval = '168h'
  auto = false
  notice = false

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = '#42a9ff'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    template = 'git:{{ if or (.Working.Changed) (.Staging.Changed) (gt .StashCount 0) }}<#ffdd86>{{ .HEAD }}</>{{ else }}{{ .HEAD }}{{ end }}{{ if .Staging.Changed }} <#98c379>{{ .Staging.String }}</>{{ end }}{{ if .Working.Changed }} <#d16971>{{ .Working.String }}</>{{ end }}'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      fetch_status = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '> '
    foreground = '#ffdd86'
    type = 'status'
    style = 'plain'
    foreground_templates = ['{{ if gt .Code 0 }}#42a9ff{{ end }}']

    [blocks.segments.properties]
      always_enabled = true
