version = 3

[palette]
arrow-foreground= "#ffdd86"
folder-foreground= "#42a9ff"
git-background = "#193549"

[upgrade]
  source = "cdn"
  interval = "168h"
  auto = false
  notice = false

[[blocks]]
  type = "prompt"
  alignment = "left"

  [[blocks.segments]]
    template = "{{ .Folder }} "
    foreground = "p:folder-foreground"
    type = "path"
    style = "plain"

    [blocks.segments.properties]
      style = "full"


  [[blocks.segments]]
    template = """\
      {{ if or (.Working.Changed) (.Staging.Changed) (gt .StashCount 0) }} \
        <#ffdd86>{{ .HEAD }}</> \
      {{ else }}\
        {{ .HEAD }} \
      {{ end }}\
      {{ if .Staging.Changed }}\
        <#98c379>{{ .Staging.String }}</> \
      {{ end }}\
      {{ if .Working.Changed }}\
        <#d16971>{{ .Working.String }}</> \
      {{ end }}\
    """
    type = "git"
    style = "plain"
    background = "p:git-background"

    [blocks.segments.properties]
      branch_icon = ""
      fetch_status = true

  [[blocks.segments]]
    template = " \u276f "
    foreground = "p:arrow-foreground"
    type = "status"
    style = "plain"

    [blocks.segments.properties]
      always_enabled = true

