if [ $SPIN ]; then
  DOTFILES_DIR=~/dotfiles
else
  DOTFILES_DIR=~/.dotfiles
fi

source $DOTFILES_DIR/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle asdf
antigen bundle brew

case `uname` in
  Darwin)
  ;;
  Linux)
  ;;
esac

antigen theme robbyrussell

antigen apply

source ~/.zsh_aliases
