source /opt/homebrew/share/antigen/antigen.zsh

antigen bundle git
antigen bundle brew
antigen bundle z
antigen bundle node
antigen bundle npm
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-autosuggestions

case `uname` in
  Darwin)
  ;;
  Linux)
  ;;
esac

antigen apply

alias gti="git"
alias gut="git"
alias be="bundle exec"
alias vi="nvim"
alias vim="nvim"

eval "$(/opt/homebrew/bin/brew shellenv)"
eval "$(/opt/homebrew/bin/mise activate zsh)"
eval "$(zoxide init zsh)"
eval "$(oh-my-posh init zsh --config '~/.dotfiles/zsh/omp.toml')"

zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]-_}={[:upper:][:lower:]_-}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' menu select
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "~/.zcompcache"

export HISTSIZE=100000

if [ -f ~/.zshrc.local ]; then
  source ~/.zshrc.local
fi
