DOTFILES_DIR=~/.dotfiles

source $DOTFILES_DIR/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle brew

case `uname` in
  Darwin)
  ;;
  Linux)
  ;;
esac

antigen theme robbyrussell
antigen apply

alias gti="git"
alias be="bundle exec"
alias vi="nvim"
alias vim="nvim"

if [ -f ~/.zshrc_local ]; then
    source ~/.zshrc_local
fi
